<img src="Covid19_guidelines_image.png" style="width: 800px;"/>

In [1]:
from bs4 import BeautifulSoup
import requests
import csv

In [3]:
# lets go to the worldmeter webapge here we need to copy this url
url = 'https://www.worldometers.info/coronavirus/'

In [4]:
#testing the url and sending request to grab HTML Data
html_page = requests.get(url).text

In [9]:
# BeautifulSoup object on the html, lxml method is a Python library which allows for easy handling of XML and HTML files, and can also be used for web scraping
soup = BeautifulSoup(html_page,'lxml')

In [12]:
#clean and proper way

In [10]:
#element

In [7]:
# we are going inspect the coronavirusd data table andget the table with all of the countries/stats
table = soup.find('table',id="main_table_countries_today")
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>4,265,256</td>
<td>+35,451</td>
<td>191,070</td>
<td>+960</td>
<td>1,994,681</td>
<td>+6,954</td>
<td>2,079,505</td>
<td>19,936</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>3,060,723</td>
<td>+11,277</td>
<td>110,594</td>
<td>+323</td>
<td>2,064,365</td>
<td>+115,045</td>
<td>885,764</td>
<td>13,699</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>3,186,881</td>
<td>+55,997</td>
<td>75,141</td>
<td>+1,254</td>
<td>2,232,648</td>
<td>+30,503</td>
<td>879,092</td>
<td>19,976</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>2,625,511</td>
<td>+11,690</td>
<td>198,107</td>
<td>+353</td>
<td>1,558,377</td>
<td>+12,211</td>
<td>869,027</td>
<td>5,279</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>648,445</td>
<td>+1,472</td>
<td>14,052</td>
<td>+23</td>
<td>337,037</td>
<td>+1,237</td>
<td>297,356</td>
<td>1,001</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>12,479</td>
<td>+324</td>
<td>135</td>
<td>+2</td>
<td>9,641</td>
<td>+108</td>
<td>2,703</td>
<td>30</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>651</td>
<td></td>
<td>55</td>
<td>4</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>13,800,016</td>
<td>+116,211</td>
<td>589,114</td>
<td>+2,915</td>
<td>8,197,400</td>
<td>+166,058</td>
<td>5,013,502</td>
<td>59,925</td>
<td>1,770</td>
<td>75.6</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">3,644,564</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+27,737</td>
<td style="font-weight: bold; text-align:right;">140,478 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+334</td>
<td style="font-weight: bold; text-align:right">1,647,032</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,070</td>
<td style="text-align:right;font-weight:bold;">1,857,054</td>
<td style="font-weight: bold; text-align:right">16,456</td>
<td style="font-weight: bold; text-align:right">11,008</td>
<td style="font-weight: bold; text-align:right">424</td>
<td style="font-weight: bold; text-align:right">45,009,054</td>
<td style="font-weight: bold; text-align:right">135,945</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,081,677</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>91</td><td>2,357</td><td>7</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">1,978,236</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,327</td>
<td style="font-weight: bold; text-align:right;">75,697 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+174</td>
<td style="font-weight: bold; text-align:right">1,366,775</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+111,211</td>
<td style="text-align:right;font-weight:bold;">535,764</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">9,304</td>
<td style="font-weight: bold; text-align:right">356</td>
<td style="font-weight: bold; text-align:right">4,911,063</td>
<td style="font-weight: bold; text-align:right">23,098</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,620,008</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>107</td><td>2,809</td><td>43</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">1,001,863</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+31,694</td>
<td style="font-weight: bold; text-align:right;">25,589 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+660</td>
<td style="font-weight: bold; text-align:right">620,194</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,459</td>
<td style="text-align:right;font-weight:bold;">356,080</td>
<td style="font-weight: bold; text-align:right">8,944</td>
<td style="font-weight: bold; text-align:right">726</td>
<td style="font-weight: bold; text-align:right">19</td>
<td style="font-weight: bold; text-align:right">12,739,490</td>
<td style="font-weight: bold; text-align:right">9,228</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,380,530,110</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>1,378</td><td>53,950</td><td>108</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">752,797</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,428</td>
<td style="font-weight: bold; text-align:right;">11,937 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+167</td>
<td style="font-weight: bold; text-align:right">531,692</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+8,443</td>
<td style="text-align:right;font-weight:bold;">209,168</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">5,158</td>
<td style="font-weight: bold; text-align:right">82</td>
<td style="font-weight: bold; text-align:right">24,053,516</td>
<td style="font-weight: bold; text-align:right">164,821</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,937,175</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>194</td><td>12,226</td><td>6</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
<td style="font-weight: bold; text-align:right">337,724</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">12,417 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">226,400</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">98,907</td>
<td style="font-weight: bold; text-align:right">1,325</td>
<td style="font-weight: bold; text-align:right">10,238</td>
<td style="font-weight: bold; text-align:right">376</td>
<td style="font-weight: bold; text-align:right">1,983,932</td>
<td style="font-weight: bold; text-align:right">60,140</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">32,988,703</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>98</td><td>2,657</td><td>17</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
<td style="font-weight: bold; text-align:right">323,698</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,493</td>
<td style="font-weight: bold; text-align:right;">7,290 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+104</td>
<td style="font-weight: bold; text-align:right">295,301</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,216</td>
<td style="text-align:right;font-weight:bold;">21,107</td>
<td style="font-weight: bold; text-align:right">1,821</td>
<td style="font-weight: bold; text-align:right">16,927</td>
<td style="font-weight: bold; text-align:right">381</td>
<td style="font-weight: bold; text-align:right">1,351,904</td>
<td style="font-weight: bold; text-align:right">70,696</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,122,661</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>59</td><td>2,623</td><td>14</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
<td style="font-weight: bold; text-align:right">317,635</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,149</td>
<td style="font-weight: bold; text-align:right;">36,906 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+579</td>
<td style="font-weight: bold; text-align:right">199,129</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,153</td>
<td style="text-align:right;font-weight:bold;">81,600</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">2,463</td>
<td style="font-weight: bold; text-align:right">286</td>
<td style="font-weight: bold; text-align:right">768,457</td>
<td style="font-weight: bold; text-align:right">5,958</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">128,984,785</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>406</td><td>3,495</td><td>168</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-africa/">South Africa</a></td>
<td style="font-weight: bold; text-align:right">311,049</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">4,453 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">160,693</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">145,903</td>
<td style="font-weight: bold; text-align:right">539</td>
<td style="font-weight: bold; text-align:right">5,242</td>
<td style="font-weight: bold; text-align:right">75</td>
<td style="font-weight: bold; text-align:right">2,278,127</td>
<td style="font-weight: bold; text-align:right">38,393</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-africa-population/">59,336,622</a> </td>
<td data-continent="Africa" style="display:none">Africa</td>
<td>191</td><td>13,325</td><td>26</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">304,574</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">28,413 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">617</td>
<td style="font-weight: bold; text-align:right">6,514</td>
<td style="font-weight: bold; text-align:right">608</td>
<td style="font-weight: bold; text-align:right">6,026,446</td>
<td style="font-weight: bold; text-align:right">128,893</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,755,564</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>154</td><td>1,646</td><td>8</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">292,552</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+641</td>
<td style="font-weight: bold; text-align:right;">45,119 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+66</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">145</td>
<td style="font-weight: bold; text-align:right">4,309</td>
<td style="font-weight: bold; text-align:right">664</td>
<td style="font-weight: bold; text-align:right">12,461,869</td>
<td style="font-weight: bold; text-align:right">183,531</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">67,900,637</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>232</td><td>1,505</td><td>5</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
<td style="font-weight: bold; text-align:right">267,061</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,500</td>
<td style="font-weight: bold; text-align:right;">13,608 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+198</td>
<td style="font-weight: bold; text-align:right">230,608</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,047</td>
<td style="text-align:right;font-weight:bold;">22,845</td>
<td style="font-weight: bold; text-align:right">3,471</td>
<td style="font-weight: bold; text-align:right">3,178</td>
<td style="font-weight: bold; text-align:right">162</td>
<td style="font-weight: bold; text-align:right">2,073,791</td>
<td style="font-weight: bold; text-align:right">24,678</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">84,033,003</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>315</td><td>6,175</td><td>41</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/pakistan/">Pakistan</a></td>
<td style="font-weight: bold; text-align:right">257,914</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,145</td>
<td style="font-weight: bold; text-align:right;">5,426 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+40</td>
<td style="font-weight: bold; text-align:right">178,737</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,927</td>
<td style="text-align:right;font-weight:bold;">73,751</td>
<td style="font-weight: bold; text-align:right">1,942</td>
<td style="font-weight: bold; text-align:right">1,167</td>
<td style="font-weight: bold; text-align:right">25</td>
<td style="font-weight: bold; text-align:right">1,652,183</td>
<td style="font-weight: bold; text-align:right">7,475</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/pakistan-population/">221,037,609</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>857</td><td>40,737</td><td>134</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">243,736</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+230</td>
<td style="font-weight: bold; text-align:right;">35,017 </td>

###### tr = table read 
###### th = table header
###### td = table data

In [13]:
# get the table header in th header
table_header = table.find('thead').find_all('th')

In [14]:
table_header

[<th width="1%">#</th>,
 <th width="100">Country,<br/>Other</th>,
 <th width="20">Total<br/>Cases</th>,
 <th width="30">New<br/>Cases</th>,
 <th width="30">Total<br/>Deaths</th>,
 <th width="30">New<br/>Deaths</th>,
 <th width="30">Total<br/>Recovered</th>,
 <th width="30">New<br/>Recovered</th>,
 <th width="30">Active<br/>Cases</th>,
 <th width="30">Serious,<br/>Critical</th>,
 <th width="30">TotÂ Cases/<br/>1M pop</th>,
 <th width="30">Deaths/<br/>1M pop</th>,
 <th width="30">Total<br/>Tests</th>,
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>,
 <th width="30">Population</th>,
 <th style="display:none" width="30">Continent</th>,
 <th width="30">1 Case<br/>every X ppl</th>,
 <th width="30">1 Death<br/>every X ppl</th>,
 <th width="30">1 Test<br/>every X ppl</th>]

In [15]:
#header
header = [] #the raw data from the header 
new_list = [] #the data after parsing it to remove newlines / other unicode characters

# get the data from the header and add it to the list
for th in table_header:
    header.append(th.text)
    
# strip the new lines and add it to the new list
for element in header:
    new_list.append(element.strip())

In [19]:
print(header)

['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/\n1M pop\n', 'Population', 'Continent', '1 Caseevery X ppl', '1 Deathevery X ppl', '1 Testevery X ppl']

In [18]:
print(new_list)

['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/\n1M pop', 'Population', 'Continent', '1 Caseevery X ppl', '1 Deathevery X ppl', '1 Testevery X ppl']

In [23]:
# remove all new lines / weird unicode chars
for i,data in enumerate(new_list):
    new_list[i] = data.replace('\xa0', '')
    new_list[i] = data.replace('\n','')
print(new_list)

['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/ 1M pop', 'Population', 'Continent', '1 Caseevery X ppl', '1 Deathevery X ppl', '1 Testevery X ppl']

In [24]:
# go through each row in the table
for row in table.find_all('tr'):

    # csvRow list used to hold the data in each row
    # empty after the data is written to the csv
    csvRow = []

    # get the data and add it to the list
    for data in row.find_all('td'):
        csvRow.append(data.text)
print(csvRow)

['', 'Total:', '13,800,016', '+116,211', '589,114', '+2,915', '8,197,400', '+166,058', '5,013,502', '59,925', '1,770.4', '75.6', '', '', '', 'All', '\n', '', '']

In [25]:
# remove all \n from the data
for i in range(len(csvRow)):
    csvRow[i] = csvRow[i].replace('\n','')

In [27]:
print(csvRow)

['', 'Total:', '13,800,016', '+116,211', '589,114', '+2,915', '8,197,400', '+166,058', '5,013,502', '59,925', '1,770.4', '75.6', '', '', '', 'All', '', '', '']